tasks:
  - init: |
      (
       sdk install java 17.0.4.1-tem < /dev/null
       curl -Ls "https://dtsx.io/get-astra-cli" | bash
       pyenv install 3.8.16 -f
       pyenv global 3.8.16
       curl -O  https://downloads.datastax.com/enterprise/cqlsh-astra-20221114-bin.tar.gz 
       tar xvfz cqlsh-astra-20221114-bin.tar.gz
       export CQLSH_PATH=./cqlsh-astra/
       mvn package -DskipTests=false
      )
    command: . setup.sh && mvn spring-boot:run
ports:
  - port: 8081
    onOpen: open-browser
